version: "3.8"

services:
  data_analizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data_analizer
    working_dir: /workspace
    volumes:
      - ./:/workspace:rw
    ports:
      - "8888:8888"
    environment:
      - TZ=UTC
    command: ["conda", "run", "-n", "myenv", "jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    restart: unless-stopped
